Rebuild for r-base 4.4 and UCRT mingw toolchain
conda-forge/r-venneuler-feedstock pull request #6
Opened 2024-10-25 16:38 UTC by danielnachun

2024-10-25 16:40 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-10-26 08:34 UTC, bgruening approved these changes

2024-10-27 12:04 UTC, mfansler requested changes

2024-10-27 12:04 UTC, mfansler commented on recipe/build.sh
> +${R} CMD INSTALL --build .
We should always pass the arguments:

```suggestion
${R} CMD INSTALL --build . ${R_ARGS}
```

2024-10-27 12:04 UTC, mfansler commented on recipe/meta.yaml
> +    - $R -e "library('venneuler')"
Please don't undo this. That is the current boilerplate and should be retained.

```suggestion
    - $R -e "library('venneuler')"           # [not win]
    - "\"%R%\" -e \"library('venneuler')\""  # [win]
```

2024-10-27 12:04 UTC, mfansler commented on recipe/meta.yaml
> -  license_family: OTHER
Please restore.

2024-10-27 12:04 UTC, mfansler commented on recipe/meta.yaml
> -{% set posix = 'm2-' if win else '' %}
Retain.

2024-10-27 12:04 UTC, mfansler commented on recipe/meta.yaml
> -    - {{ posix }}zip               # [win]
Retain.

2024-10-27 12:10 UTC, mfansler commented
Hi @danielnachun. Since you're joining the team, maybe let's be a bit more strict about keeping the standard that would come out of `conda_r_skeleton_helper` rather than cutting off what might currently seem as unnecessary. The advantage to keeping the Windows boilerplate around is that all our recipes are robust to readily convertible to non-`noarch`.

Also, in the future please always commit your changes first, then run a `conda-smithy rerender` and commit with the suggested commit message. That provides a transparent record of when rerendering was done and the exact version of `conda-forge-pinning` that was applied.

2024-10-27 17:27 UTC, danielnachun commented
Thanks @mfansler, I wasn't sure if those `#[win]` lines were leftovers that are supposed to be removed for `noarch` packages since I was mostly fixing non-`noarch` packages until now.  I guess for new R recipe submission in conda-forge they might result in linting failures, but for existing ones it's obviously allowed.  I'll also fix up my commit messages for the rerenders.  I guess I can use the bot to rerender most of the time after commit my manual changes as I've seen you do before.  I'll make sure to double check with other R maintainers before merging anything I'm not sure about.

2024-10-29 19:54 UTC, danielnachun commented
I resolved all the requested changes here and made the same changes to the other PRs I made for license issues as well, so I'm going to merge them now.

2024-10-29 19:54 UTC, merged